import { earlyRegistrationSubmitSchema } from "@enrollpro/shared";
import type { z } from "zod";

export const EarlyRegFormSchema = earlyRegistrationSubmitSchema;
export type EarlyRegFormData = z.infer<typeof earlyRegistrationSubmitSchema>;

export const DEFAULT_VALUES: Partial<EarlyRegFormData> = {
  schoolYear: "",
  gradeLevel: "7",
  lrn: "",
  hasNoLrn: false,
  learnerType: "NEW_ENROLLEE",
  isScpApplication: false,
  scpType: null,
  studentPhoto: undefined,
  lastName: "",
  firstName: "",
  middleName: "",
  extensionName: "",
  birthdate: "",
  sex: "MALE",
  placeOfBirth: "",
  religion: "",
  isIpCommunity: false,
  ipGroupName: "",
  isLearnerWithDisability: false,
  disabilityTypes: [],
  houseNoStreet: "",
  sitio: "",
  barangay: "",
  cityMunicipality: "",
  province: "",
  father: {
    lastName: "",
    firstName: "",
    middleName: "",
    contactNumber: "",
    email: "",
  },
  mother: {
    maidenName: "",
    firstName: "",
    middleName: "",
    contactNumber: "",
    email: "",
  },
  guardian: {
    lastName: "",
    firstName: "",
    middleName: "",
    contactNumber: "",
    email: "",
  },
  guardianRelationship: "",
  primaryContact: null,
  hasNoMother: false,
  hasNoFather: false,
  contactNumber: "",
  email: "",
  isPrivacyConsentGiven: false,
};
